services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  test_db:
    image: postgres:16
    container_name: test_db
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: unless-stopped

  api:
    build: backend
    container_name: api
    image: api:2
    env_file: backend/.env
    networks:
      - frontend
      - backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend/src:/service/src
      - ./backend/tests:/service/tests
      - ./backend/migrations:/service/migrations
      - app_static:/service/static
      - app_media:/service/media
    restart: unless-stopped

networks:
  frontend:
  backend:

volumes:
  test_postgres_data:
  postgres_data:
  app_static:
  app_media: