FROM python:3.12.1-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV IS_DOCKER_CONTAINER 1

WORKDIR /service

COPY pyproject.toml .

RUN pip install --upgrade pip
RUN pip install poetry

RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

COPY migrations migrations
COPY src src
COPY tests tests

COPY alembic.ini .

EXPOSE 8080

CMD bash -c "poe migrate && poe start"