"""ref

Revision ID: 38fc61660d2d
Revises: c5875d57229f
Create Date: 2024-09-09 17:57:34.865061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38fc61660d2d"
down_revision: Union[str, None] = "c5875d57229f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "order", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "user_id")
    # ### end Alembic commands ###
