"""ref2

Revision ID: 5e222c53960f
Revises: 38fc61660d2d
Create Date: 2024-09-09 17:58:43.173359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e222c53960f"
down_revision: Union[str, None] = "38fc61660d2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_user_id_fkey", "order", type_="foreignkey")
    op.drop_column("order", "user_id")
    op.drop_constraint("pizza_user_id_fkey", "pizza", type_="foreignkey")
    op.drop_column("pizza", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pizza",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "pizza_user_id_fkey", "pizza", "user", ["user_id"], ["id"]
    )
    op.add_column(
        "order",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "order_user_id_fkey", "order", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
