"""Pizza category can be null

Revision ID: 6c448e04a22f
Revises: 8c3d0c946aa5
Create Date: 2024-09-10 19:08:50.154631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c448e04a22f"
down_revision: Union[str, None] = "8c3d0c946aa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pizza", "category_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pizza", "category_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
