"""Pizza Category

Revision ID: 8c3d0c946aa5
Revises: 33f2e3a28d52
Create Date: 2024-09-10 19:04:27.714517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c3d0c946aa5"
down_revision: Union[str, None] = "33f2e3a28d52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pizza_category",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("pizza", sa.Column("category_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "pizza", "pizza_category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pizza", type_="foreignkey")
    op.drop_column("pizza", "category_id")
    op.drop_table("pizza_category")
    # ### end Alembic commands ###
