"""association table

Revision ID: b2d216df60d7
Revises: 577b16de0098
Create Date: 2024-09-10 08:20:36.272045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2d216df60d7"
down_revision: Union[str, None] = "577b16de0098"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pizza_size_association",
        sa.Column("pizza_id", sa.UUID(), nullable=False),
        sa.Column("pizza_size_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizza.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pizza_size_id"],
            ["pizza_size.id"],
        ),
        sa.PrimaryKeyConstraint("pizza_id", "pizza_size_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pizza_size_association")
    # ### end Alembic commands ###
