"""pizza: money description

Revision ID: bea3102cd1d4
Revises: dcd2eb21a5b8
Create Date: 2024-09-07 15:57:53.785725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bea3102cd1d4"
down_revision: Union[str, None] = "dcd2eb21a5b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pizza", sa.Column("description", sa.TEXT(), nullable=True))
    op.add_column(
        "pizza",
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pizza", "price")
    op.drop_column("pizza", "description")
    # ### end Alembic commands ###
