"""order order_item coupon

Revision ID: c5875d57229f
Revises: 68681fc5b24e
Create Date: 2024-09-09 16:20:30.613148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5875d57229f"
down_revision: Union[str, None] = "68681fc5b24e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupon",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("payment_id", sa.String(), nullable=True),
        sa.Column("coupon_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_item",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("pizza_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizza.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "pizza",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "profile", "bio", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_unique_constraint(None, "profile", ["user_id"])
    op.create_unique_constraint(None, "user", ["email"])
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "profile", type_="unique")
    op.alter_column(
        "profile", "bio", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "pizza",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.drop_table("order_item")
    op.drop_table("order")
    op.drop_table("coupon")
    # ### end Alembic commands ###
