"""relation between user and pizza

Revision ID: ebac30ae9600
Revises: 5e222c53960f
Create Date: 2024-09-10 07:24:02.739981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebac30ae9600"
down_revision: Union[str, None] = "5e222c53960f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pizza", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "pizza", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pizza", type_="foreignkey")
    op.drop_column("pizza", "user_id")
    # ### end Alembic commands ###
